version: '3'
services:
    api:
        build: ./api 
        container_name: covid-search-demo
        volumes:
            - './api:/usr/src/app/covid-ai2'
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - 'PYTHONUNBUFFERED=1'
            - 'LOG_LEVEL=DEBUG'
    proxy:
        build: ./proxy
        ports:
            - '8080:80'
