version: '3'
services:
    sonar:
        build: ./sonar
    
    demo-env:
    
        build: ./demo-env
        image: covid-demo-basis
    
    api:
        image: covid-demo-basis
        build: ./api
        container_name: covid-search-demo
        volumes:
            - './api:/usr/local/src/skiff/app/api'
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - 'PYTHONUNBUFFERED=1'
            - 'LOG_LEVEL=DEBUG'
    proxy:
        build: ./proxy
        ports:
            - '8080:80'
